In [0]:
#This is a cell

2b) 
just use the button, duh
Execute: Strg-Enter

Stop a running cell: Strg-C
Run All: Strg-F9


In [0]:
import numpy as np
x = np.zeros((3,2,4))
x


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [0]:
y = np.reshape(x,(2,-1))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
y[1,1]

0.0

In [0]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
y[:,1]

array([0., 0.])

In [0]:
x = np.arange(0,50)
x = np.reshape(x,(5,10))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
np.shape(x)

(5, 10)

Derivative:
f(x) --> f'(x)
x^n --> nx^n-1
(Power Rule)

Chain Rule:
dx(x) = dx(x outer) * dx(x inner)

compute min/max:
set derivative = 0, then solve, because the min/max will have a slope of 0
global: biggest/smallest overall
local: dx(x) = 0 == true, but a different global mx/min exists
Saddlepoint= dx(x) == true, but no slope inversion occurs