In [0]:
import numpy as np

In [0]:
x = np.array([0,0,-10])
n = np.array([0,0,1])
eye = np.array([0,0,0])
y1 = np.array([5,0,-5])
y2 = np.array([0,5,-5])
c1 = np.array([1,0,0])
c2 = np.array([0,0,1])
C_a = np.identity(3)*0.3
C_d = np.identity(3)*0.7
C_s = np.identity(3)*0.1
s = 10
v = (eye-x)/np.linalg.norm(eye-x)
l1 = (y1-x)/np.linalg.norm(y1-x)
l2 = (y2-x)/np.linalg.norm(y2-x)
r1 = 2*l1.T@n*n-l1
r2 = 2*l2.T@n*n-l2

In [0]:
r11 = 2*n*(n.T@l1)-l1
print(r11)
print(r1)

[-0.70710678  0.          0.70710678]
[-0.70710678  0.          0.70710678]


In [0]:
r2

array([ 0.        , -0.70710678,  0.70710678])

In [0]:
Light1 = (C_a+C_d*np.max([0,l1.T@n])+C_s*np.max([0, v.T@r1])**s)*c1
Light2 = (C_a+C_d*np.max([0,l2.T@n])+C_s*np.max([0, v.T@r2])**s)*c2
phong = Light1 + Light2

In [0]:
Light2

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.80961941]])

In [0]:
h1 = (v-l1)/np.linalg.norm(v-l1)
h2 = (v-l2)/np.linalg.norm(v-l2)
s_blinn = 2

Light1 = (C_a+C_d*np.max([0,l1.T@n])+C_s*np.max([0, h1.T@n])**s_blinn)*c1
Light2 = (C_a+C_d*np.max([0,l2.T@n])+C_s*np.max([0, h2.T@n])**s_blinn)*c2
Blinn = Light1 + Light2

In [0]:
h1

array([-0.92387953,  0.        ,  0.38268343])

In [0]:
Blinn

array([[0.80961941, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.80961941]])

In [0]:
phong

array([[0.79809975, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.79809975]])

In [0]:
((8*16*-21)-(-8*16*-21))/6

-896.0